export default {
    THEME_CHANGE:'THEME_CHANGE', // 主题改变
    THEME_INIT:'THEME_INIT', // 主题初始化
    POPULAR_REFRESH:'POPULAR_REFRESH', //最热模块 下拉加载更多
    POPULAR_REFRESH_FAIL:'POPULAR_REFRESH_FAIL', //最热模块 下拉加载更多失败
    POPULAR_REFRESH_SUCCESS:'POPULAR_REFRESH_SUCCESS', //最热模块 下拉加载更多成功
    POPULAR_LOAD_MORE_SUCCESS:'POPULAR_LOAD_MORE_SUCCESS', //最热模块 上拉加载更多成功
    POPULAR_LOAD_MORE_FAIL:'POPULAR_LOAD_MORE_FAIL', //最热模块 上拉加载更多失败
}