export default {
    THEME_CHANGE:'THEME_CHANGE', // 主题改变
    THEME_INIT:'THEME_INIT', // 主题初始化

    /**
     * 最热模块状态
     */
    POPULAR_REFRESH:'POPULAR_REFRESH', //下拉刷新
    POPULAR_REFRESH_FAIL:'POPULAR_REFRESH_FAIL', //下拉刷新失败
    POPULAR_REFRESH_SUCCESS:'POPULAR_REFRESH_SUCCESS', //下拉刷新成功
    POPULAR_LOAD_MORE_SUCCESS:'POPULAR_LOAD_MORE_SUCCESS', //上拉加载更多成功
    POPULAR_LOAD_MORE_FAIL:'POPULAR_LOAD_MORE_FAIL', //上拉加载更多失败

    /**
     * 趋势模块状态
     */
    TRENDING_REFRESH:'TRENDING_REFRESH', //下拉刷新
    TRENDING_REFRESH_FAIL:'TRENDING_REFRESH_FAIL', //下拉刷新失败
    TRENDING_REFRESH_SUCCESS:'TRENDING_REFRESH_SUCCESS', //下拉刷新成功
    TRENDING_LOAD_MORE_SUCCESS:'TRENDING_LOAD_MORE_SUCCESS', //上拉加载更多成功
    TRENDING_LOAD_MORE_FAIL:'TRENDING_LOAD_MORE_FAIL', //上拉加载更多失败


}